version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck
    - gocritic
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/go-php/gateway
  staticcheck:
    checks:
      - all
      - "-SA1012"
      - "-SA9003"
      - "-QF1003"
      - "-QF1012"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
