run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - unconvert
    - gocritic
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/go-php/gateway
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-tags:
      - performance
      - experimental

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
