package fpm

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DirectiveLayer represents a layer of PHP configuration directives.
type DirectiveLayer struct {
	Name       string
	Priority   int
	Directives map[string]string
}

// ConfigLayering manages PHP configuration through multiple layers.
type ConfigLayering struct {
	Layers []DirectiveLayer
}

// NewConfigLayering creates an empty config layering system.
func NewConfigLayering() *ConfigLayering {
	return &ConfigLayering{}
}

// AddLayer adds a configuration layer.
func (cl *ConfigLayering) AddLayer(name string, priority int, directives map[string]string) {
	cl.Layers = append(cl.Layers, DirectiveLayer{
		Name:       name,
		Priority:   priority,
		Directives: directives,
	})
}

// Merge produces the final merged directives, later layers override earlier ones.
func (cl *ConfigLayering) Merge() map[string]string {
	// Sort by priority.
	sorted := make([]DirectiveLayer, len(cl.Layers))
	copy(sorted, cl.Layers)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Priority < sorted[j].Priority
	})

	result := make(map[string]string)
	for _, layer := range sorted {
		for k, v := range layer.Directives {
			result[k] = v
		}
	}
	return result
}

// GenerateINI produces a php.ini compatible file from merged directives.
func (cl *ConfigLayering) GenerateINI() string {
	merged := cl.Merge()

	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("; Auto-generated by gateway php config layering\n\n")

	currentSection := ""
	for _, k := range keys {
		section := sectionForDirective(k)
		if section != currentSection {
			b.WriteString(fmt.Sprintf("\n[%s]\n", section))
			currentSection = section
		}
		b.WriteString(fmt.Sprintf("%s = %s\n", k, merged[k]))
	}

	return b.String()
}

// WriteINI writes the merged php.ini to a file.
func (cl *ConfigLayering) WriteINI(dir string) (string, error) {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("create ini dir: %w", err)
	}

	path := filepath.Join(dir, "gateway-php.ini")
	content := cl.GenerateINI()

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("write php.ini: %w", err)
	}

	return path, nil
}

// DirectiveClassification determines if a directive is safe to set.
type DirectiveClassification string

const (
	ClassSafe       DirectiveClassification = "safe"
	ClassWarning    DirectiveClassification = "warning"
	ClassRestricted DirectiveClassification = "restricted"
	ClassOwned      DirectiveClassification = "owned" // gateway controls this
)

// ClassifyDirective returns the classification of a PHP directive.
func ClassifyDirective(name string) DirectiveClassification {
	restricted := map[string]bool{
		"disable_functions":  true,
		"disable_classes":    true,
		"open_basedir":       true,
		"safe_mode":          true,
		"safe_mode_exec_dir": true,
	}

	owned := map[string]bool{
		"error_log":       true,
		"log_errors":      true,
		"display_errors":  true,
		"error_reporting": true,
		"date.timezone":   true,
	}

	if restricted[name] {
		return ClassRestricted
	}
	if owned[name] {
		return ClassOwned
	}

	// Warning-level: performance/critical settings.
	warning := map[string]bool{
		"memory_limit":               true,
		"max_execution_time":         true,
		"max_input_time":             true,
		"post_max_size":              true,
		"upload_max_filesize":        true,
		"max_file_uploads":           true,
		"opcache.enable":             true,
		"opcache.memory_consumption": true,
	}

	if warning[name] {
		return ClassWarning
	}

	return ClassSafe
}

func sectionForDirective(name string) string {
	switch {
	case strings.HasPrefix(name, "opcache."):
		return "opcache"
	case strings.HasPrefix(name, "session."):
		return "Session"
	case strings.HasPrefix(name, "pdo_"):
		return "PDO"
	case strings.HasPrefix(name, "mbstring."):
		return "mbstring"
	default:
		return "PHP"
	}
}

// DefaultDevDirectives returns standard development directives.
func DefaultDevDirectives() map[string]string {
	return map[string]string{
		"error_reporting":        "E_ALL",
		"display_errors":         "On",
		"display_startup_errors": "On",
		"log_errors":             "On",
		"error_log":              "/dev/stderr",
		"memory_limit":           "256M",
		"max_execution_time":     "0",
		"date.timezone":          "UTC",
		"opcache.enable":         "0",
		"opcache.enable_cli":     "0",
	}
}

// DefaultProdDirectives returns standard production directives.
func DefaultProdDirectives() map[string]string {
	return map[string]string{
		"error_reporting":                 "E_ALL & ~E_DEPRECATED & ~E_STRICT",
		"display_errors":                  "Off",
		"display_startup_errors":          "Off",
		"log_errors":                      "On",
		"error_log":                       "/var/log/php-errors.log",
		"memory_limit":                    "128M",
		"max_execution_time":              "30",
		"date.timezone":                   "UTC",
		"opcache.enable":                  "1",
		"opcache.enable_cli":              "0",
		"opcache.memory_consumption":      "128",
		"opcache.interned_strings_buffer": "16",
		"opcache.max_accelerated_files":   "10000",
		"opcache.validate_timestamps":     "0",
		"session.cookie_httponly":         "1",
		"session.cookie_secure":           "1",
		"session.use_strict_mode":         "1",
	}
}
